/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Conrad Justin (https://sketchfab.com/ConradJustin)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/the-last-stronghold-animated-6b4ac951cefb43a791b2bd084b53a201
Title: The Last Stronghold (animated)
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import * as THREE from 'three'
import { TextureLoader } from 'three';

export default function Magic(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/the_last_stronghold_animated.glb')
  const { actions } = useAnimations(animations, group)

  const carbonTexture = useLoader(TextureLoader, '/texture-2.jpeg');
    carbonTexture.wrapS = THREE.RepeatWrapping;
    carbonTexture.wrapT = THREE.RepeatWrapping;
    carbonTexture.repeat.set(3, 3);
    carbonTexture.flipY = false;
    carbonTexture.colorSpace = THREE.SRGBColorSpace;
  
    const carbonMaterial = new THREE.MeshStandardMaterial({
      map: carbonTexture,
      metalness: 1,
      roughness: 1,
    });

  useEffect(() => {
          if (actions) {
            Object.values(actions).forEach((action) => action.play()) // Hammasini ishga tushiramiz
          }
        }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002}>
          <group name="ed9a8042c54c452db47145e9a7551210fbx" rotation={[-Math.PI, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="merged_gate" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate003" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate005" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate006" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate007" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate008" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate009" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate010" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate011" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate012" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="Armature" rotation={[0, 0, -Math.PI / 2]} scale={100}>
                  <group name="Object_15">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_18"
                      geometry={nodes.Object_18.geometry}
                      material={carbonMaterial}
                      skeleton={nodes.Object_18.skeleton}
                    />
                    <skinnedMesh
                      name="Object_20"
                      geometry={nodes.Object_20.geometry}
                         material={carbonMaterial}
                      skeleton={nodes.Object_20.skeleton}
                    />
                    <skinnedMesh
                      name="Object_22"
                      geometry={nodes.Object_22.geometry}
                      material={carbonMaterial}
                      skeleton={nodes.Object_22.skeleton}
                    />
                    <skinnedMesh
                      name="Object_24"
                      geometry={nodes.Object_24.geometry}
                      material={carbonMaterial}
                      skeleton={nodes.Object_24.skeleton}
                    />
                    <skinnedMesh
                      name="Object_26"
                      geometry={nodes.Object_26.geometry}
                      material={carbonMaterial}
                      skeleton={nodes.Object_26.skeleton}
                    />
                    <skinnedMesh
                      name="Object_28"
                      geometry={nodes.Object_28.geometry}
                      material={carbonMaterial}
                      skeleton={nodes.Object_28.skeleton}
                    />
                    <skinnedMesh
                      name="Object_30"
                      geometry={nodes.Object_30.geometry}
                      material={carbonMaterial}
                      skeleton={nodes.Object_30.skeleton}
                    />
                    <skinnedMesh
                      name="Object_32"
                      geometry={nodes.Object_32.geometry}
                      material={carbonMaterial}
                      skeleton={nodes.Object_32.skeleton}
                    />
                    <skinnedMesh
                      name="Object_34"
                      geometry={nodes.Object_34.geometry}
                      material={carbonMaterial}
                      skeleton={nodes.Object_34.skeleton}
                    />
                    <skinnedMesh
                      name="Object_36"
                      geometry={nodes.Object_36.geometry}
                      material={carbonMaterial}
                      skeleton={nodes.Object_36.skeleton}
                    />
                    <group name="Object_17" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_19" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_21" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_23" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_25" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_27" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_29" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_31" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_33" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_35" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/the_last_stronghold_animated.glb')
