/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shaurya_Jaiswal (https://sketchfab.com/jaiswalshaurya1310)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/valorant-chamber-card-470c47fc303743a38f3cde693c42dc10
Title: Valorant Chamber Card
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function card(props) {
  const { nodes, materials } = useGLTF('/valorant_chamber_card.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Chambers_card_0"
                position={[2.114, 37.613, 2.573]}
                rotation={[Math.PI / 2, -0.175, Math.PI / 2]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials['Material.003']}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials['Material.004']}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/valorant_chamber_card.glb')
