/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ArachnoBoy (https://sketchfab.com/vang807)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/godzilla-01b0d48490d24e2d868f96660e4be671
Title: Godzilla
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Godzilla(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/godzilla.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
        if (actions) {
          Object.values(actions).forEach((action) => action.play()) // Hammasini ishga tushiramiz
        }
      }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={17.486}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]} scale={0.159}>
                <group name="root_1">
                  <group name="GLTF_SceneRootNode_2" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="root_132_3" scale={0.08}>
                      <group name="GLTF_created_0_4">
                        <group name="GLTF_created_0">
                          <primitive object={nodes.GLTF_created_0_rootJoint} />
                          <skinnedMesh
                            name="Object_143"
                            geometry={nodes.Object_143.geometry}
                            material={materials.Golzilla_pbs}
                            skeleton={nodes.Object_143.skeleton}
                          />
                          <group name="Object_7_7_correction">
                            <group name="Object_7_7" />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/godzilla.glb')
