/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ivandrodejesues908 (https://sketchfab.com/ivandrodejesues908)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jordan-4-retro-travis-scott-purple-e055428e1f294a73b5e6518a4f902c04
Title: Jordan 4 Retro Travis Scott "Purple"
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Jordan(props) {
  const { nodes, materials } = useGLTF('/jordan_4_retro_travis_scott_purple.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="619dd104800049dd8d420f910a99bd0cfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="RootNode">
              <group
                name="Travis_x_Scott_Cactus_Jack_x_Air_Jordan_4_High_Retro_mat_00"
                position={[0, 16.608, 8.007]}
                rotation={[-2.906, 0, 0]}
                scale={222.814}>
                <mesh
                  name="Travis_x_Scott_Cactus_Jack_x_Air_Jordan_4_High_Retro_mat_00_mat_0003_0"
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Travis_x_Scott_Cactus_Jack_x_Air_Jordan_4_High_Retro_mat_00_mat_0003_0
                      .geometry
                  }
                  material={materials['mat_0.003']}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/jordan_4_retro_travis_scott_purple.glb')
