/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: d.csngr (https://sketchfab.com/d.csngr)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/y2k-sport-sunglass-1895aa504a4e434bbac2a7b6fffe35d8
Title: Y2K Sport Sunglass
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SunGlass(props) {
  const { nodes, materials } = useGLTF('/y2k_sport_sunglass.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Dark_Shade}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          // material={materials.White_Plastic}
        >
          <meshPhysicalMaterial metalness={1} color={'red'} roughness={1} ior={0.4} />  
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.White_Plastic}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/y2k_sport_sunglass.glb')
